- hosts: localhost
  connection: local
  tasks:
    - name: create a VPC with dedicated tenancy and a couple of tags
      amazon.aws.ec2_vpc_net:
         name: test
         cidr_block: 10.10.0.0/16
         region: us-east-1
         tags:
           module: ec2_vpc_net
           this: works
         tenancy: dedicated


